### PR TITLE
Update readme.md with OS installation.

### PR DESCRIPTION
**Pull request by SSSSam141**
OS installation readme file done.

### CODE REVIEW

**Comment by KaneBetter** [comment]
LGTM, thank you, Sam

**Review by KaneBetter — APPROVED** [review]
LGTM, thank you, Sam

**Comment by omarcostahamido** [comment]
this closed #13

**Comment by omarcostahamido** [comment]
@SSSSam141 if it is safe to do so, please delete the `SSSSam141-patch-1` branch, so that we don't have extra branches laying around that are not being worked on and have already been merged.

**Pull request merged**
